### ISSUE TITLE
Chef 14.14 - undefined method `mongodb_user' for cookbook: sc-mongodb, recipe: user_management :Chef::Recipe

### ISSUE THREAD

**Issue by davidalpert** [sous-chefs/sc-mongodb#272]
## :ghost: Brief Description

Since `provides :mongodb_user` was removed from `./resources/user.rb` in PR #262 the `mongodb_user` resource in `./recipes/user_management.rb` can fail to compile since the cookbook name isn't `mongodb` but is `sc-mongodb`

## :pancakes: Cookbook version

`4.1.0`

## :woman_cook:  Chef-Infra Version

`14.14.29`

## :tophat: Platform details

Centos 7

## Steps To Reproduce

1. create a simple cookbook with a dependency on `sc-mongodb` `v4.1.0`
2. add an `attributes/default.rb` file which sets `default['mongodb']['users']` as described in this cookbook's documentation
3. add a `recipes/default.rb` which simply includes `sc-mogodb::user_management`
4. converge on a Centos 7 VM running chef-client 14.14.29

## :police_car: Expected behavior

The `sc-mongodb::user_management` recipe runs and creates the configured `node['mongodb']['users']`

## :police_car: Actual behavior

The `sc-mongodb::user_management` recipe fails to compile with this error:
```
  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/nfl-forge/recipes/mongo.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `mongodb_user' for cookbook: sc-mongodb, recipe: user_management :Chef::Recipe

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/sc-mongodb/recipes/user_management.rb:37:in `block in from_file'
    /var/chef/cache/cookbooks/sc-mongodb/recipes/user_management.rb:36:in `each'
    /var/chef/cache/cookbooks/sc-mongodb/recipes/user_management.rb:36:in `from_file'
    /var/chef/cache/cookbooks/undefined-user-test/recipes/default.rb:2:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/sc-mongodb/recipes/user_management.rb:

   30:  # add the admin to the users array for adding/updating
   31:  users << admin if (node['mongodb']['config']['auth'] == true) || (node['mongodb']['mongos_create_admin'] == true)
   32:
   33:  users.concat(node['mongodb']['users'])
   34:
   35:  # Add each user specified in attributes
   36:  users.each do |user|
   37>>   mongodb_user user['username'] do
   38:      password user['password']
   39:      roles user['roles']
   40:      database user['database']
   41:      connection node['mongodb']
   42:      if node.recipe?('sc-mongodb::mongos') || node.recipe?('sc-mongodb::replicaset')
   43:        # If it's a replicaset or mongos, don't make any users until the end
   44:        action :nothing
   45:        subscribes :add, 'ruby_block[config_replicaset]', :delayed
   46:        subscribes :add, 'ruby_block[config_sharding]', :delayed

  System Info:
  ------------
  chef_version=14.14.29
  platform=centos
  platform_version=7.7.1908
  ruby=ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
  program_name=/usr/bin/chef-client
  executable=/opt/chef/bin/chef-client
```
## :heavy_plus_sign: Additional context

It appears that after removing this line https://github.com/sous-chefs/mongodb/pull/262/files#diff-857a2a3b37af7381d1ed290cd3d9c0fdb19707e682628695cef1fb3551d2db1cL1 the assumed name of the resource defined in `./resources/user.rb` is not `mongodb_user` as is referenced here https://github.com/sous-chefs/mongodb/blob/4.1.0/recipes/user_management.rb#L37 but is actually `sc_mongodb_user` (since the cookbook `metadata.rb` defines the cookbook name as `sc-mongodb`)

I tested this locally and if I update here https://github.com/sous-chefs/mongodb/blob/4.1.0/recipes/user_management.rb#L37 to look like this:
```ruby
# Add each user specified in attributes
users.each do |user|
  sc_mongodb_user user['username'] do
    password user['password']
    roles user['roles']
```
then it compiles and converges fine with chef-client `14.14.29`

alternatively I can compile and converge by downgrading my `sc-mongodb` reference to lock it at `4.0.1`.

**Comment by ramereth** [comment]
@davidalpert this should be an easy fix by defining the provider name in the resource to be the previous name. Do you think you can make a PR which addresses this?

**Comment by davidalpert** [comment]
here is what I propose:

- add to both the `./resources/user.rb` and `./resources/agent.rb` resource definitions a pair of guarded name helpers like this:

    ```ruby
    # these helpers ensure that the base name of this resources is 'mongodb' instead of inheriting the 'sc-mongodb' cookbook name
    provides :mongodb_user if respond_to?(:provides)
    resource_name 'mongodb_user' if respond_to?(:resource_name)
    ```

that covers both older and newer naming methods and should be backwards compatible in the sense that each method is protected by a guard clause.

It's not clear to me how to run the chefspec or kitchen/inspec tests in this cookbook.  without a Gemfile I find I'm stumbling over gem version compatibility issues trying to run `rspec` or `kitchen list`

is this change small enough that you would accept it without test evidence?  alternatively, if you can help me understand how to run the tests locally I would be happy to attempt to replicate the bug with test coverage before fixing it.

**Comment by davidalpert** [comment]
I found the runtime gems specified in `./attributes/default.rb` (`default['mongodb']['ruby_gems']`) 

what if we added a `Gemfile` with only development dependencies? this might allow us to specify the gem versions compatible with the chefspec and kitchen/inspec tests without requiring any specific gem versions to use the cookbook.

**Comment by ramereth** [comment]
> here is what I propose:
> 
> * add to both the `./resources/user.rb` and `./resources/agent.rb` resource definitions a pair of guarded name helpers like this:
>   ```ruby
>   # these helpers ensure that the base name of this resources is 'mongodb' instead of inheriting the 'sc-mongodb' cookbook name
>   provides :mongodb_user if respond_to?(:provides)
>   resource_name 'mongodb_user' if respond_to?(:resource_name)
>   ```
> 
> that covers both older and newer naming methods and should be backwards compatible in the sense that each method is protected by a guard clause.

This is correct however you don't need to do the guard clauses as these should be present in Chef >=14 which this cookbook requires.

> It's not clear to me how to run the chefspec or kitchen/inspec tests in this cookbook. without a Gemfile I find I'm stumbling over gem version compatibility issues trying to run `rspec` or `kitchen list`

It's best to run this with Chef Workstation as it has all of the gem dependencies you need to properly test it. We shouldn't need to touch the Gemfile in this cookbook.

> is this change small enough that you would accept it without test evidence? alternatively, if you can help me understand how to run the tests locally I would be happy to attempt to replicate the bug with test coverage before fixing it.

If you're having trouble getting Chef Workstation working, you can also use the docker image and test that way. If that's still too much of a problem, I recommend you just make a PR and our CI system will do the tests for you.

Thanks!

**Comment by davidalpert** [comment]
I haven't tried yet to get Chef Workstation working on my machine as we are still supporting older cookbooks and pinned as a team to ChefDK 13.10.12.

the PR is up at https://github.com/sous-chefs/mongodb/pull/274 and available or review. some of the checks failed but appear to be linting issues which were also failing in the last approved PR

**Comment by ramereth** [comment]
I'll see if I can fix the linting issues in a separate PR first.

**Comment by davidalpert** [comment]
this all seems resolved now.

I have simplified and rebased PR #274 onto `main` and all the tests are passing.

**Comment by davidalpert** [comment]
I can confirm that `4.1.3` now converges for me in test kitchen against Chef 14.14.29 and gets past #200
